### ISSUE TITLE
Could Not Find Task?

### ISSUE THREAD

**Issue by philjulian** [jamesb93/nimBend#7]
I have R and Nim / Nimble installed here on a Mac. When I cd to the main Mosh folder and run `nimble installRelease` I get:

Error: Could not find task installRelease in /Users/pmj/Desktop/mosh-main/mosh.nimble
      Hint: Run `nimble --help` and/or `nimble tasks` for a list of possible commands.

Doubtless a newbie error, is there anything specific I should try to get around this?  Or anything outside of R and Nimble I should make sure I have?

**Comment by jamesb93** [comment]
Try `nimble install`. I need to update the README as its super out of date.

**Comment by philjulian** [comment]
Thanks, that works and creates files at ~/.nimble/bin but any attempt to use mosh or look at the -h returns:

-bash: mosh: command not found

mosh exec is definitely there under /pkgs/mosh-0.5.0 so not sure what I'm missing.  This is on an old Mac (High Sierra) if that has any bearing on it?

**Comment by jamesb93** [comment]
That is because `~/.nimble/bin` is not in your path. I' surprised it creates it at that path though. On my machine it creates it in the repo folder. You should be able to run it from there once its installed with `./mosh` (where `/.` dictates that you are looking in _this_ folder.

**Comment by philjulian** [comment]
Hmmm, bit out of my depth here clearly (didn't take long)

I downloaded the repo and have it on my desktop.  It has created a mosh exec in that folder and again under ~/.nimble/bin

If I cd to the desktop repo and run the mosh commands it throws that bash error.  Not sure what you mean by installing it under ./mosh (complete newbie stuff here I'm afraid)

**Comment by jamesb93** [comment]
Okay so ignore the one that is created in `~/.nimble/bin`. He's dead to us.

I assume you have invoked something like `cd ~/Desktop/mosh` to get into the repo.

You can then run `./mosh -h` _assuming you are in the repo in your terminal_. Can always setup a quick zoom call to get you going if you like.

**Comment by philjulian** [comment]
Got it!  Works a treat.  Really appreciate the help, thanks James.

**Comment by jamesb93** [comment]
> Got it! Works a treat. Really appreciate the help, thanks James.

No problem, have fun :)
