### ISSUE TITLE
Compile failing

### ISSUE THREAD

**Issue by radiophonic** [jamesb93/nimBend#8]
Hello and thank you for the code. I would love to play with this tool, however it fails to compile with the following error:

`[my path]/config.nims(1, 2) Error: 'none', 'boehm' or 'refc' expected, but 'orc' found`

Are there binaries for Linux available to download?

**Comment by jamesb93** [comment]
hi, sorry for the delay. Try now with the latest on `main`?

**Comment by radiophonic** [comment]
No worries, thanks for the response.

I thought maybe it was a problem with the version of nimble that's installed, however I cannot even upgrade nimble without the same type of error. I'll report back.

**Comment by radiophonic** [comment]
Follow-up: The nim installation for Linux Mint 20.3 Una was no good. I did a manual install via the instructions on the nim web site.

Mosh compiles fine now. Apologies for the report. I'll file a report with Mint regarding the nim install.

Have a great day!

**Comment by jamesb93** [comment]
No worries. I think using `choosenim` is always the best bit with managing the Nim version.
